pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=dependabot[bot]
      - check-success=Lint
      - check-success=Test
    actions:
      merge:
        method: squash